name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
    example:
        description: No hago nada xDDDDD Bla Bla
        permission: bullnexmc.normal
        usage: /<command>
    update:
        description: Actualiza el plugin a la nueva version
        permission: bullnexmc.update
        usage: /<command>
    bn-size:
        description: Devuelve el tamaño del plugin
        permission: bullnexmc.update
        usage: /<command>
    bn-drop:
        description: Hace caer un bloque
        permission: bullnexmc.update
        usage: /<command> <x> <y> <z>

permissions:
    bullnexmc.update:
        description: Permiso para actualizar el plugin
        default: op