name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
    example:
        description: An example command
        permission: spigotplugin.example
        usage: /<command>
    update:
        description: Actualiza el plugin
        permission: spigotplugin.example
        usage: /<command>
    location:
        description: Devuelve el path del plugin
        permission: spigotplugin.example
        usage: /<command>

permissions: {}