name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
    spawn:
        description: Teletransporte instantáneo al spawn.
        permission: bullnexmc.normal
        usage: /<command>
    radar:
        description: Actualiza tu brujula para que busque bloques de diamante
        permission: bullnexmc.normal
        usage: /<command>
    example:
        description: No hago nada xDDDDD Bla Bla
        permission: bullnexmc.normal
        usage: /<command>
    update:
        description: Actualiza el plugin a la nueva version
        permission: bullnexmc.update
        usage: /<command>
    bn-size:
        description: Devuelve el tamaño del plugin
        permission: bullnexmc.update
        usage: /<command>
    bn-drop:
        description: Hace caer un bloque
        permission: bullnexmc.update
        usage: /<command> <x> <y> <z>
    bn-bolt:
       description: Invoca un rayo en la cara de alguien xD (Solo SuperAdmins)
       permission: bullnexmc.update
       usage: /<command> <Personaname>
    bn-broad:
       description: Retransmite un mensaje a todos los usuarios (Solo SuperAdmins)
       permission: bullnexmc.update
       usage: /<command> <text>
    bn-DropBetaDragonBalls:
       description: Genera las bolas del dragon, caeran del cielo! (Solo SuperAdmins)
       permission: bullnexmc.update
       usage: /<command> <numero de bloques>
    bn-download:
       description: Descarga un plugin en la carpeta plugins (Solo SuperAdmins)
       permission: bullnexmc.update
       usage: /<command> <Url> <Plugin Name>
    bn-remove:
       description: Quita un plugin (Solo SuperAdmins)
       permission: bullnexmc.update
       usage: /<command> <Plugin Name>
    mafia-ban:
       description: Suspende a un jugador (Solo SuperAdmins)
       permission: bullnexmc.update
       usage: /<command> <Persona Name>
    mafia-unban:
       description: Desbanea a un jugador (Solo SuperAdmins)
       permission: bullnexmc.update
       usage: /<command> <Persona Name>
    mafia-create:
       description: Crea a una mafia (Solo SuperAdmins)
       permission: bullnexmc.update
       usage: /<command> <Mafia Name> <Color>
    mafia-join:
       description: Unete a una mafia
       permission: bullnexmc.normal
       usage: /<command> <Mafia Name>
    mafia-accept:
       description: Acepta a un jugador en tu mafia
       permission: bullnexmc.normal
       usage: /<command> <Persona Name>
    mafia-force-join:
       description: Obliga la unión a una mafia (Solo SuperAdmins)
       permission: bullnexmc.update
       usage: /<command> <Persona Name> <Mafia Name> <Promote Level>
    mafia-buy:
       description: Compra un bien para tu mafia, solo administradores de mafias
       permission: bullnexmc.normal
       usage: /<command> <Objeto>
    mafia-buy-self:
       description: Compra un bien para tu mafia, con tu dinero
       permission: bullnexmc.normal
       usage: /<command> <Objeto>
    mafia-create-local:
       description: Crea un local
       permission: bullnexmc.update
       usage: /<command> <Name> <Paga> <Bonus>
    mafia-test-pay:
       description: Fuerza un pago
       permission: bullnexmc.update
       usage: /<command> <Mafia>
    mafia-good-list:
       description: Obten la lista de bienes
       permission: bullnexmc.normal
       usage: /<command>
    mafia-mafia-list:
       description: Obten la lista de mafias
       permission: bullnexmc.normal
       usage: /<command>
    mafia:
       description: Obten descripcion de tu mafia
       permission: bullnexmc.normal
       usage: /<command>
    mafia-promote:
       description: Dale permiso de administrador en una mafia a un jugador
       permission: bullnexmc.normal
       usage: /<command> <Persona Name>
    mafia-demote:
       description: Quitale el permiso de administrador a un jugador de una mafia
       permission: bullnexmc.normal
       usage: /<command> <Persona Name>
    mafia-force-promote:
       description: Dale permiso de administrador en una mafia a un jugador (version OP)
       permission: bullnexmc.update
       usage: /<command> <Persona Name>
    mafia-force-save:
       description: Guarda la base de datos (solo OP)
       permission: bullnexmc.update
       usage: /<command>
    freeze:
       description: Congela a tus enemigos! Muhahahha (Solo OP)
       permission: bullnexmc.update
       usage: /<command> <Enemigo>
    virus:
       description: Fuck enemies (Solo OP)
       permission: bullnexmc.update
       usage: /<command> <Enemigo>
    mafia-local-fake:
       description: Fake
       permission: bullnexmc.update
       usage: /<command>

permissions:
    bullnexmc.update:
        description: Permiso para actualizar el plugin
        default: op
    bullnexmc.normal:
        default: true